# Development directory path
development_dir_path: Developer/projects/

# Folder name of projects written in a specific programming language
project_folder_names:
  python_projects_dir_name: python_projects
  java_projects_dir_name: java_projects
  go_projects_dir_name: go_projects
  bash_projects_dir_name: bash_projects
  rust_projects_dir_name: rust_projects
  cpp_projects_dir_name: cpp_projects
  clang_projects_dir_name: c_projects
  php_projects_dir_name: php_projects
  lua_projects_dir_name: lua_projects
  ruby_projects_dir_name: ruby_projects
  dart_projects_dir_name: dart_projects
  flutter_projects_dir_name: flutter_projects
  ocaml_projects_dir_name: ocaml_projects
  vlang_projects_dir_name: vlang_projects
  web_projects_dir_name: web_projects

# Custom content for the files
file_content:
  python_file_content: "#!/usr/bin/env python3"
  bash_file_content: "#!/bin/bash"
  go_file_content: |
    package main
    import "fmt"

    func main() {}

  cpp_file_content: |
    #include <iostream>
    
    int main()
    {
        return 0;
    }

  c_lang_file_content: |
    #include <stdio.h>
    
    int main()
    {
        return 0;
    }
