# Development directory path
development_dir_path: Developer/projects/

# Default content of the .gitignore file
default_gitignore_content: |
  .DS_Store
  .env
  .vscode/
  .idea/
  test/

# Bash
bash:
  projects_dir_name: bash_projects
  file_content: "#!/bin/bash"
  gitignore_content: ""

# C
c_lang:
  projects_dir_name: c_projects
  file_content: |
    #include <stdio.h>

    int main()
    {
        return 0;
    }
  gitignore_content: ""

# CPP
cpp:
  projects_dir_name: cpp_projects
  file_content: |
    #include <iostream>

    int main()
    {
        return 0;
    }
  gitignore_content: ""

# Go
go:
  projects_dir_name: go_projects
  file_content: |
    package main
    import "fmt"

    func main() {}
  gitignore_content: ""

# Java
java:
  projects_dir_name: java_projects
  file_content: ""
  gitignore_content: ""

# Lua
lua:
  projects_dir_name: lua_projects
  file_content: ""
  gitignore_content: ""

# OCaml
ocaml:
  projects_dir_name: ocaml_projects

# PHP
php:
  projects_dir_name: php_projects
  file_content: ""
  gitignore_content: ""

# Python
python:
  projects_dir_name: python_projects
  file_content: "#!/usr/bin/env python3"
  gitignore_content: |
    .DS_Store
    .env
    .vscode/
    .idea/
    test/
    venv/
    __pycache__/

# Ruby
ruby:
  projects_dir_name: ruby_projects

# Rust
rust:
  projects_dir_name: rust_projects

# Vlang
vlang:
  projects_dir_name: vlang_projects

# Web projects
web:
  projects_dir_name: web_projects
  html_file_content: ""
  css_file_content: ""
  javascript_file_content: ""
  gitignore_content: ""
