#!/usr/bin/env python3

from typing import Final

DEVELOPMENT_DIR_NOT_FOUND_ERROR: Final[int] = 300
PROJECTS_FOLDER_NOT_FOUND_ERROR: Final[int] = 301
PROJECT_ALREADY_EXISTS_ERROR: Final[int] = 302
INVALID_PROJECT_NAME: Final[int] = 303
YAML_CONFIG_FILE_NOT_FOUND_ERROR: Final[int] = 304
YAML_CONFIG_FILE_GENERIC_ERROR: Final[int] = 305
JSON_SCHEMA_FILE_NOT_FOUND_ERROR: Final[int] = 306
PYTHON_VENV_ERROR: Final[int] = 307
README_ERROR: Final[int] = 308
COMMAND_ERROR: Final[int] = 309
COMMAND_NOT_FOUND_ERROR: Final[int] = 310
GITIGNORE_ERROR: Final[int] = 311
GIT_ERROR: Final[int] = 312
GIT_NOT_INSTALLED: Final[int] = 313
IDE_NOT_FOUND_ERROR: Final[int] = 314
CREATE_OR_WRITE_ERROR: Final[int] = 315
