name: newproject-cli-tests

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'crash_test/**'
      - 'tests/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'crash_test/**'
      - 'tests/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        os: [ ubuntu-latest, macOS-latest ]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov newproject-cli
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # default set of ruff rules with GitHub Annotations
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create development directory
        run: |
          mkdir -p $HOME/Developer/projects
      - name: Test with pytest and collect coverage
        run: |
          pytest --cov .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}

